version: '3.8'
name: user-service

services:
  user-service:
    build: .
    container_name: user_service
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - users-db
      - redis
    networks:
      - user-network

  users-db:
    image: postgres:17.5
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - user-network

  redis:
    image: redis:7.4
    container_name: users_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - user-network

volumes:
  users_data:
  redis_data:

networks:
  user-network:
    driver: bridge