server:
  port: 4000

spring:
  application:
    name: user-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/users_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  liquibase:
    change-log: classpath:db/changelog/app-changelog.xml

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}

logging:
  level:
    liquibase: DEBUG
