spring:
  application:
    name: user-service

  liquibase:
    change-log: classpath:db/changelog/app-changelog.xml

  cache:
    type: redis

logging:
  level:
    liquibase: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true