server:
  port: 4000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/users_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6380

service:
  internal:
    api-key: secret
  auth:
    url: http://localhost:4001

management:
  zipkin:
    tracing:
      endpoint: mock