name: user-service
version: '3.8'

services:
  users-db:
    image: postgres:17.5
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4
    container_name: users_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  users_data:
  redis_data:
